namespace Aspire.Hosting.AspireC4.Lifecycle;

public sealed partial class AspireC4LifecycleHookTests
{
	[Test]
	public async Task StripHeader_StandardGeneratedHeader_ReturnsBodyWithoutTimestamp()
	{
		// Arrange
		var content = string.Join(
			"\n",
			"// =============================================================================",
			"// AUTO-GENERATED by AspireC4 — 2025-01-15 12:34:56 UTC",
			"// Do not edit this file manually. Any changes will be overwritten on the",
			"// next diagram regeneration (on Aspire startup or resource state change).",
			"// See https://github.com/purview-dev/aspirec4 for more information.",
			"// =============================================================================",
			"",
			"specification {",
			"  element component",
			"}"
		);

		// Act
		var body = AspireC4LifecycleHook.StripHeader(content);

		// Assert
		await Assert.That(body).StartsWith("\nspecification {");
		await Assert.That(body).DoesNotContain("AUTO-GENERATED");
		await Assert.That(body).DoesNotContain("2025-01-15");
		await Assert.That(body).Contains("specification {");
	}

	[Test]
	public async Task StripHeader_TwoDifferentTimestamps_ProducesIdenticalBodies()
	{
		// Arrange
		// Simulate two generations of the same model at different timestamps.
		static string MakeContent(string timestamp) =>
			string.Join(
				"\n",
				"// =============================================================================",
				$"// AUTO-GENERATED by AspireC4 — {timestamp} UTC",
				"// Do not edit this file manually. Any changes will be overwritten on the",
				"// next diagram regeneration (on Aspire startup or resource state change).",
				"// See https://github.com/purview-dev/aspirec4 for more information.",
				"// =============================================================================",
				"",
				"specification {",
				"  tag aspire-run-state-running",
				"}",
				"",
				"model {",
				"  api = component 'API'",
				"}"
			);

		var content1 = MakeContent("2025-01-15 12:00:00");
		var content2 = MakeContent("2025-01-15 12:00:05");

		// Act
		var body1 = AspireC4LifecycleHook.StripHeader(content1);
		var body2 = AspireC4LifecycleHook.StripHeader(content2);

		// Assert — same model content → same stripped body, skip write possible.
		await Assert.That(body1).IsEqualTo(body2);
	}

	[Test]
	public async Task StripHeader_DifferentModelContent_ProducesDifferentBodies()
	{
		// Arrange
		static string MakeContent(string extraTag) =>
			string.Join(
				"\n",
				"// =============================================================================",
				"// AUTO-GENERATED by AspireC4 — 2025-01-15 12:00:00 UTC",
				"// =============================================================================",
				"",
				$"specification {{ tag {extraTag} }}"
			);

		var content1 = MakeContent("external");
		var content2 = MakeContent("deprecated");

		// Act
		var body1 = AspireC4LifecycleHook.StripHeader(content1);
		var body2 = AspireC4LifecycleHook.StripHeader(content2);

		// Assert — different model → different bodies, write must proceed.
		await Assert.That(body1).IsNotEqualTo(body2);
	}

	[Test]
	public async Task StripHeader_NoHeaderDelimiter_ReturnsFullContent()
	{
		// Arrange
		var content = "specification {\n  element component\n}";

		// Act
		var body = AspireC4LifecycleHook.StripHeader(content);

		// Assert — no delimiter found, full content returned unchanged.
		await Assert.That(body).IsEqualTo(content);
	}

	[Test]
	public async Task StripHeader_OnlyOneDelimiterLine_ReturnsFullContent()
	{
		// Arrange
		var content =
			"// =============================================================================\nspecification { }";

		// Act
		var body = AspireC4LifecycleHook.StripHeader(content);

		// Assert — only one delimiter present, cannot strip safely, returns full content.
		await Assert.That(body).IsEqualTo(content);
	}
}
