using Aspire.Hosting.ApplicationModel;
using Aspire.Hosting.AspireC4.LikeC4.Models;

namespace Aspire.Hosting.AspireC4.LikeC4.Generators;

public sealed partial class LikeC4DSLGeneratorTests
{
	static readonly AspireC4DiagramOptions DefaultOptions = new()
	{
		Title = "Test Architecture",
		ViewTitle = "Test Architecture",
		OutputDirectory = "./likec4",
		FileName = "model.gen",
	};

	[Test]
	public async Task Generate_EmptyModel_ProducesMinimalValidDsl()
	{
		// Arrange

		// Act
		var dsl = LikeC4DSLGenerator.Generate(LikeC4Model.Empty, DefaultOptions);

		// Should produce valid structure even with no elements.
		// Assert
		await Assert.That(dsl).Contains("specification {");
		await Assert.That(dsl).Contains("model {");
		await Assert.That(dsl).Contains("views {");
		await Assert.That(dsl).Contains("view index {");
	}

	[Test]
	public async Task Generate_AlwaysEmitsAutoGeneratedHeader()
	{
		// Arrange
		var before = DateTimeOffset.UtcNow;
		// Act
		var dsl = LikeC4DSLGenerator.Generate(LikeC4Model.Empty, DefaultOptions);
		var after = DateTimeOffset.UtcNow;

		// Assert
		await Assert.That(dsl).StartsWith("//");
		await Assert.That(dsl).Contains("AUTO-GENERATED by AspireC4");
		await Assert.That(dsl).Contains("Do not edit this file manually");

		// Timestamp in the header must fall within the test window.
		var match = TimeStampRegex().Match(dsl);
		await Assert.That(match.Success).IsTrue();
		var timestamp = DateTimeOffset.ParseExact(
			match.Groups[1].Value,
			"yyyy-MM-dd HH:mm:ss",
			System.Globalization.CultureInfo.InvariantCulture,
			System.Globalization.DateTimeStyles.AssumeUniversal
		);
		await Assert.That(timestamp).IsGreaterThanOrEqualTo(before.AddSeconds(-1));
		await Assert.That(timestamp).IsLessThanOrEqualTo(after.AddSeconds(1));
	}

	[Test]
	public async Task Generate_SingleElement_IncludesKindInSpecification()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("element component");
	}

	[Test]
	public async Task Generate_MultipleKinds_AllKindsInSpecification()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "db",
					Label = "DB",
					Kind = LikeC4ElementKind.Database,
				},
				new LikeC4Element
				{
					Name = "cache",
					Label = "Cache",
					Kind = LikeC4ElementKind.Container,
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("element component");
		await Assert.That(dsl).Contains("element database");
		await Assert.That(dsl).Contains("element container");
	}

	[Test]
	public async Task Generate_DuplicateKinds_KindAppearsOnceInSpecification()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api1",
					Label = "API 1",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "api2",
					Label = "API 2",
					Kind = LikeC4ElementKind.Component,
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		var count = CountOccurrences(dsl, "element component");
		// Assert
		await Assert.That(count).IsEqualTo(1);
	}

	[Test]
	public async Task Generate_ElementWithTechnology_IncludesTechnologyLine()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
					Technology = "ASP.NET Core",
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("technology 'ASP.NET Core'");
	}

	[Test]
	public async Task Generate_ElementWithDescription_IncludesDescriptionLine()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
					Description = "Handles HTTP requests",
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("description '''");
		await Assert.That(dsl).Contains("Handles HTTP requests");
	}

	[Test]
	public async Task Generate_ElementWithIcon_IncludesIconLine()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "db",
					Label = "DB",
					Kind = LikeC4ElementKind.Database,
					Icon = "tech:postgresql",
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("icon tech:postgresql");
	}

	[Test]
	public async Task Generate_LabelWithSingleQuote_IsEscaped()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "O'Brien's API",
					Kind = LikeC4ElementKind.Component,
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains(@"'O\'Brien\'s API'");
	}

	[Test]
	public async Task Generate_NameWithSpecialChars_IsSanitized()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "my-api.service",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("my_api_service = component");
	}

	[Test]
	public async Task Generate_Relationship_RenderedAsArrow()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "db",
					Label = "DB",
					Kind = LikeC4ElementKind.Database,
				},
			],
			Relationships = [new LikeC4Relationship { SourceName = "api", TargetName = "db" }],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("api -> db");
	}

	[Test]
	public async Task Generate_RelationshipWithLabel_IncludesLabel()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "queue",
					Label = "Queue",
					Kind = LikeC4ElementKind.System,
				},
			],
			Relationships =
			[
				new LikeC4Relationship
				{
					SourceName = "api",
					TargetName = "queue",
					Label = "Publishes",
				},
			],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("api -> queue 'Publishes'");
		// label-only: the relationship line should NOT open a block
		await Assert.That(dsl).DoesNotContain("api -> queue 'Publishes' {");
	}

	[Test]
	public async Task Generate_RelationshipWithTechnology_EmitsBlock()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "db",
					Label = "DB",
					Kind = LikeC4ElementKind.Database,
				},
			],
			Relationships =
			[
				new LikeC4Relationship
				{
					SourceName = "api",
					TargetName = "db",
					Technology = "PostgreSQL",
				},
			],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("api -> db {");
		await Assert.That(dsl).Contains("technology 'PostgreSQL'");
	}

	[Test]
	public async Task Generate_RelationshipWithDescription_EmitsBlock()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "db",
					Label = "DB",
					Kind = LikeC4ElementKind.Database,
				},
			],
			Relationships =
			[
				new LikeC4Relationship
				{
					SourceName = "api",
					TargetName = "db",
					Description = "Stores user data",
				},
			],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("api -> db {");
		await Assert.That(dsl).Contains("description '''");
		await Assert.That(dsl).Contains("Stores user data");
	}

	[Test]
	public async Task Generate_RelationshipWithLabelAndTechnology_EmitsBoth()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "cache",
					Label = "Cache",
					Kind = LikeC4ElementKind.Container,
				},
			],
			Relationships =
			[
				new LikeC4Relationship
				{
					SourceName = "api",
					TargetName = "cache",
					Label = "Caches data",
					Technology = "Redis Protocol",
				},
			],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("api -> cache 'Caches data' {");
		await Assert.That(dsl).Contains("technology 'Redis Protocol'");
	}

	[Test]
	public async Task Generate_RelationshipWithKind_EmitsTypedSyntaxInModel()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "queue",
					Label = "Queue",
					Kind = LikeC4ElementKind.System,
				},
			],
			Relationships =
			[
				new LikeC4Relationship
				{
					SourceName = "api",
					TargetName = "queue",
					Kind = "async",
				},
			],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("api .async queue");
	}

	[Test]
	public async Task Generate_RelationshipWithKind_DeclaredInSpecification()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "queue",
					Label = "Queue",
					Kind = LikeC4ElementKind.System,
				},
			],
			Relationships =
			[
				new LikeC4Relationship
				{
					SourceName = "api",
					TargetName = "queue",
					Kind = "async",
				},
			],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("relationship async");
	}

	[Test]
	public async Task Generate_RelationshipWithKindAndLabel_EmitsTypedSyntaxWithLabel()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "queue",
					Label = "Queue",
					Kind = LikeC4ElementKind.System,
				},
			],
			Relationships =
			[
				new LikeC4Relationship
				{
					SourceName = "api",
					TargetName = "queue",
					Kind = "async",
					Label = "Publishes",
				},
			],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("api .async queue 'Publishes'");
	}

	[Test]
	public async Task Generate_RelationshipWithKind_BracketSyntax_EmitsBracketForm()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "queue",
					Label = "Queue",
					Kind = LikeC4ElementKind.System,
				},
			],
			Relationships =
			[
				new LikeC4Relationship
				{
					SourceName = "api",
					TargetName = "queue",
					Kind = "async",
				},
			],
		};
		AspireC4DiagramOptions opts = new()
		{
			Title = "Test",
			OutputDirectory = ".",
			RelationshipKindSyntax = LikeC4RelationshipKindSyntax.Bracket,
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, opts);

		// Assert
		await Assert.That(dsl).Contains("api -[async]-> queue");
	}

	[Test]
	public async Task Generate_RelationshipWithKindAndLabel_BracketSyntax_EmitsBracketForm()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "queue",
					Label = "Queue",
					Kind = LikeC4ElementKind.System,
				},
			],
			Relationships =
			[
				new LikeC4Relationship
				{
					SourceName = "api",
					TargetName = "queue",
					Kind = "async",
					Label = "Publishes",
				},
			],
		};
		AspireC4DiagramOptions opts = new()
		{
			Title = "Test",
			OutputDirectory = ".",
			RelationshipKindSyntax = LikeC4RelationshipKindSyntax.Bracket,
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, opts);

		// Assert
		await Assert.That(dsl).Contains("api -[async]-> queue 'Publishes'");
	}

	[Test]
	public async Task Generate_MultipleRelationshipsWithSameKind_KindAppearsOnceInSpecification()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "queue1",
					Label = "Queue 1",
					Kind = LikeC4ElementKind.System,
				},
				new LikeC4Element
				{
					Name = "queue2",
					Label = "Queue 2",
					Kind = LikeC4ElementKind.System,
				},
			],
			Relationships =
			[
				new LikeC4Relationship
				{
					SourceName = "api",
					TargetName = "queue1",
					Kind = "async",
				},
				new LikeC4Relationship
				{
					SourceName = "api",
					TargetName = "queue2",
					Kind = "async",
				},
			],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		var count = CountOccurrences(dsl, "relationship async");
		// Assert
		await Assert.That(count).IsEqualTo(1);
	}

	[Test]
	public async Task Generate_MultipleRelationshipsWithDifferentKinds_AllKindsDeclaredInSpecification()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "db",
					Label = "DB",
					Kind = LikeC4ElementKind.Database,
				},
				new LikeC4Element
				{
					Name = "queue",
					Label = "Queue",
					Kind = LikeC4ElementKind.System,
				},
			],
			Relationships =
			[
				new LikeC4Relationship
				{
					SourceName = "api",
					TargetName = "db",
					Kind = "sql",
				},
				new LikeC4Relationship
				{
					SourceName = "api",
					TargetName = "queue",
					Kind = "async",
				},
			],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("relationship async");
		await Assert.That(dsl).Contains("relationship sql");
	}

	[Test]
	public async Task Generate_RelationshipWithoutKind_DoesNotAddRelationshipSpecification()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "db",
					Label = "DB",
					Kind = LikeC4ElementKind.Database,
				},
			],
			Relationships = [new LikeC4Relationship { SourceName = "api", TargetName = "db" }],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).DoesNotContain("relationship ");
		await Assert.That(dsl).Contains("api -> db");
	}

	[Test]
	public async Task Generate_RelationshipKindSpecification_AppearsInsideSpecificationBlock()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "queue",
					Label = "Queue",
					Kind = LikeC4ElementKind.System,
				},
			],
			Relationships =
			[
				new LikeC4Relationship
				{
					SourceName = "api",
					TargetName = "queue",
					Kind = "async",
				},
			],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		var specIdx = dsl.IndexOf("specification {", StringComparison.Ordinal);
		var specCloseIdx = dsl.IndexOf('}', specIdx);
		var relKindIdx = dsl.IndexOf("relationship async", StringComparison.Ordinal);
		var modelIdx = dsl.IndexOf("model {", StringComparison.Ordinal);

		// Assert
		await Assert.That(relKindIdx).IsGreaterThan(specIdx);
		await Assert.That(relKindIdx).IsLessThan(specCloseIdx);
		await Assert.That(relKindIdx).IsLessThan(modelIdx);
	}

	[Test]
	public async Task Generate_RelationshipKindSpec_WithTechnology_EmitsTechnologyBlock()
	{
		// Arrange
		AspireC4DiagramOptions opts = new()
		{
			Title = "Test",
			OutputDirectory = ".",
			RelationshipKindSpecs = [new LikeC4RelationshipKindSpec("async").WithTechnology("AMQP")],
		};

		LikeC4Model model = new() { Elements = [], Relationships = [] };

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, opts);

		// Assert
		await Assert.That(dsl).Contains("relationship async {");
		await Assert.That(dsl).Contains("technology 'AMQP'");
		await Assert.That(dsl).Contains("}");
	}

	[Test]
	public async Task Generate_RelationshipKindSpec_WithoutTechnology_EmitsSingleLine()
	{
		// Arrange
		AspireC4DiagramOptions opts = new()
		{
			Title = "Test",
			OutputDirectory = ".",
			RelationshipKindSpecs = [new LikeC4RelationshipKindSpec("grpc")],
		};

		LikeC4Model model = new() { Elements = [], Relationships = [] };

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, opts);

		// Assert — bare single-line form, no block body
		await Assert.That(dsl).Contains("relationship grpc");
		await Assert.That(dsl).DoesNotContain("relationship grpc {");
		await Assert.That(dsl).DoesNotContain("technology '");
	}

	[Test]
	public async Task Generate_RelationshipKindSpec_DeclaredEvenWhenNotUsedInModel()
	{
		// Arrange
		AspireC4DiagramOptions opts = new()
		{
			Title = "Test",
			OutputDirectory = ".",
			RelationshipKindSpecs = [new LikeC4RelationshipKindSpec("event-driven").WithTechnology("Kafka")],
		};

		LikeC4Model model = new() { Elements = [], Relationships = [] };

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, opts);

		// Assert — spec-only kind still appears in specification block
		await Assert.That(dsl).Contains("relationship event-driven {");
		await Assert.That(dsl).Contains("technology 'Kafka'");
	}

	[Test]
	public async Task Generate_RelationshipKindFromModel_WithMatchingSpec_EmitsTechnologyBlock()
	{
		// Arrange
		AspireC4DiagramOptions opts = new()
		{
			Title = "Test",
			OutputDirectory = ".",
			RelationshipKindSpecs = [new LikeC4RelationshipKindSpec("grpc").WithTechnology("gRPC")],
		};

		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "svc",
					Label = "Svc",
					Kind = LikeC4ElementKind.Component,
				},
			],
			Relationships =
			[
				new LikeC4Relationship
				{
					SourceName = "api",
					TargetName = "svc",
					Kind = "grpc",
				},
			],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, opts);

		// Assert — spec body used instead of bare line; kind appears exactly once in specification
		await Assert.That(dsl).Contains("relationship grpc {");
		await Assert.That(dsl).Contains("technology 'gRPC'");
		var count = CountOccurrences(dsl, "relationship grpc");
		await Assert.That(count).IsEqualTo(1);
	}

	[Test]
	public async Task Generate_RelationshipKindSpec_TechnologyWithSingleQuote_IsEscaped()
	{
		// Arrange
		AspireC4DiagramOptions opts = new()
		{
			Title = "Test",
			OutputDirectory = ".",
			RelationshipKindSpecs = [new LikeC4RelationshipKindSpec("msg").WithTechnology("O'Brien protocol")],
		};

		LikeC4Model model = new() { Elements = [], Relationships = [] };

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, opts);

		// Assert — single quote inside value is escaped
		await Assert.That(dsl).Contains("O\\'Brien protocol");
	}

	[Test]
	public async Task Generate_ViewContainsTitle()
	{
		// Arrange

		// Act
		var dsl = LikeC4DSLGenerator.Generate(LikeC4Model.Empty, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("title 'Test Architecture'");
	}

	[Test]
	public async Task Generate_DefaultGeneratedViewId_EmitsIndexView()
	{
		// Arrange

		// Act
		var dsl = LikeC4DSLGenerator.Generate(LikeC4Model.Empty, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("view index {");
	}

	[Test]
	public async Task Generate_CustomGeneratedViewId_UsesCustomId()
	{
		// Arrange
		AspireC4DiagramOptions opts = new()
		{
			Title = DefaultOptions.Title,
			OutputDirectory = DefaultOptions.OutputDirectory,
			FileName = DefaultOptions.FileName,
			GeneratedViewId = "overview",
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(LikeC4Model.Empty, opts);

		// Assert
		await Assert.That(dsl).Contains("view overview {");
		await Assert.That(dsl).DoesNotContain("view index {");
	}

	[Test]
	public async Task Generate_NullOrWhitespaceGeneratedViewId_FallsBackToIndex()
	{
		// Arrange
		AspireC4DiagramOptions optsNull = new()
		{
			Title = DefaultOptions.Title,
			OutputDirectory = DefaultOptions.OutputDirectory,
			FileName = DefaultOptions.FileName,
			GeneratedViewId = null,
		};
		AspireC4DiagramOptions optsEmpty = new()
		{
			Title = DefaultOptions.Title,
			OutputDirectory = DefaultOptions.OutputDirectory,
			FileName = DefaultOptions.FileName,
			GeneratedViewId = "   ",
		};

		// Act
		var dslNull = LikeC4DSLGenerator.Generate(LikeC4Model.Empty, optsNull);
		var dslEmpty = LikeC4DSLGenerator.Generate(LikeC4Model.Empty, optsEmpty);

		// Assert
		await Assert.That(dslNull).Contains("view index {");
		await Assert.That(dslEmpty).Contains("view index {");
	}

	[Test]
	public async Task DefaultViewId_DefaultsToIndex()
	{
		// Arrange
		AspireC4DiagramOptions opts = new();

		// Act

		// Assert
		await Assert.That(opts.DefaultViewId).IsEqualTo("index");
	}

	[Test]
	public async Task DefaultViewId_WhenNull_IsNull()
	{
		// Arrange
		AspireC4DiagramOptions opts = new() { DefaultViewId = null };

		// Act

		// Assert
		await Assert.That(opts.DefaultViewId).IsNull();
	}

	[Test]
	public async Task DefaultViewId_WhenCustomValue_ReturnsCustomValue()
	{
		// Arrange
		AspireC4DiagramOptions opts = new() { DefaultViewId = "context" };

		// Act

		// Assert
		await Assert.That(opts.DefaultViewId).IsEqualTo("context");
	}

	[Test]
	public async Task Generate_TitleWithSingleQuote_IsEscaped()
	{
		// Arrange
		AspireC4DiagramOptions opts = new() { ViewTitle = "O'Reilly's App", OutputDirectory = "." };

		// Act
		var dsl = LikeC4DSLGenerator.Generate(LikeC4Model.Empty, opts);

		// Assert
		await Assert.That(dsl).Contains(@"title 'O\'Reilly\'s App'");
	}

	[Test]
	public async Task Generate_NonEmptyModel_ViewContainsIncludeStar()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("include *");
	}

	[Test]
	public async Task Generate_NestedElement_RenderedInsideParent()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "postgres",
					Label = "Postgres",
					Kind = LikeC4ElementKind.Container,
				},
				new LikeC4Element
				{
					Name = "appdb",
					Label = "App DB",
					Kind = LikeC4ElementKind.Database,
					ParentName = "postgres",
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// The child should appear inside the parent's block
		var postgresIdx = dsl.IndexOf("postgres = container", StringComparison.Ordinal);
		var appdbIdx = dsl.IndexOf("appdb = database", StringComparison.Ordinal);
		// Assert
		await Assert.That(postgresIdx).IsLessThan(appdbIdx);
		// Parent block should be opened before child
		var braceIdx = dsl.IndexOf('{', postgresIdx);
		await Assert.That(braceIdx).IsLessThan(appdbIdx);
	}

	static int CountOccurrences(string source, string substring)
	{
		var count = 0;
		var idx = 0;
		while ((idx = source.IndexOf(substring, idx, StringComparison.Ordinal)) >= 0)
		{
			count++;
			idx += substring.Length;
		}

		return count;
	}

	[Test]
	[MethodDataSource(nameof(StateStyleMappings))]
	public async Task Generate_ElementWithState_RendersExpectedStyle(
		string? state,
		string? stateTag,
		string? expectedColor,
		int? expectedOpacity
	)
	{
		// Arrange
		var tags = stateTag is not null ? (IReadOnlyList<string>)[stateTag] : [];
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
					State = state,
					Tags = tags,
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		var viewsIdx = dsl.IndexOf("views {", StringComparison.Ordinal);
		var modelSection = dsl[..viewsIdx];

		if (expectedColor is null)
		{
			// No state tag on this element — the model section should not contain color or opacity.
			// The views section will still contain all default state style rules (always emitted).
			await Assert.That(modelSection).DoesNotContain("color ");
			await Assert.That(modelSection).DoesNotContain("opacity ");
		}
		else
		{
			// Color override must appear inside the tag-predicate style rule in the views section.
			await Assert.That(dsl).Contains($"style element.tag = #{stateTag}");
			await Assert.That(dsl).Contains($"color {expectedColor}");

			var colorIdx = dsl.IndexOf($"color {expectedColor}", viewsIdx, StringComparison.Ordinal);
			await Assert.That(colorIdx).IsGreaterThan(viewsIdx);

			// Opacity is checked only within the specific style block for this tag, because
			// other state blocks (e.g. stopping, exited) always emit their own opacity values.
			var styleBlockStart = dsl.IndexOf($"style element.tag = #{stateTag}", viewsIdx, StringComparison.Ordinal);
			var styleBlockOpen = dsl.IndexOf('{', styleBlockStart);
			var styleBlockClose = dsl.IndexOf('}', styleBlockOpen);
			var styleBlockContent = dsl[styleBlockOpen..styleBlockClose];

			// Stopping (60%) is more visible than Exited/Finished (30%).
			if (expectedOpacity is not null)
			{
				await Assert.That(styleBlockContent).Contains($"opacity {expectedOpacity}%");
			}
			else
			{
				await Assert.That(styleBlockContent).DoesNotContain("opacity ");
			}
		}
	}

	/// <summary>
	/// State → (tag, color, opacity) style mappings.
	/// <para>
	/// Opacity differentiates transitional from terminal states:
	/// <list type="bullet">
	///   <item><description>Stopping: 60 % — transitional, winding down but still visible.</description></item>
	///   <item><description>Exited: 30 % — terminal, clearly faded/inactive.</description></item>
	/// </list>
	/// </para>
	/// </summary>
	public static IEnumerable<(string? State, string? StateTag, string? Color, int? Opacity)> StateStyleMappings()
	{
		yield return (null, null, null, null);
		yield return (KnownResourceStates.Starting, "aspire-run-state-starting", "sky", null);
		yield return (KnownResourceStates.Waiting, "aspire-run-state-waiting", "sky", null);
		yield return (KnownResourceStates.Running, "aspire-run-state-running", "green", null);
		yield return (KnownResourceStates.Stopping, "aspire-run-state-stopping", "slate", 60);
		yield return (KnownResourceStates.Exited, "aspire-run-state-exited", "muted", 30);
		yield return (KnownResourceStates.Finished, "aspire-run-state-finished", "muted", 30);
		yield return (KnownResourceStates.RuntimeUnhealthy, "aspire-run-state-runtimeunhealthy", "amber", null);
		yield return (KnownResourceStates.FailedToStart, "aspire-run-state-failedtostart", "red", null);
	}

	[Test]
	public async Task Generate_ElementWithStateAndTechnology_RendersColorInViewsNotModel()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
					Technology = ".NET",
					State = KnownResourceStates.FailedToStart,
					Tags = ["aspire-run-state-failedtostart"],
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Technology stays in model block.
		// Assert
		await Assert.That(dsl).Contains("technology '.NET'");

		// Color must be in views section only.
		var viewsIdx = dsl.IndexOf("views {", StringComparison.Ordinal);
		var colorIdx = dsl.IndexOf("color red", StringComparison.Ordinal);
		await Assert.That(colorIdx).IsGreaterThan(viewsIdx);

		// model block must NOT contain color.
		var modelSection = dsl[..viewsIdx];
		await Assert.That(modelSection).DoesNotContain("color");
	}

	[Test]
	public async Task Generate_ElementWithIconAndState_RendersIconInModelAndColorInViews()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
					Icon = "tech:dotnet",
					State = KnownResourceStates.Running,
					Tags = ["aspire-run-state-running"],
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		var viewsIdx = dsl.IndexOf("views {", StringComparison.Ordinal);
		var iconIdx = dsl.IndexOf("icon tech:dotnet", StringComparison.Ordinal);
		var colorIdx = dsl.IndexOf("color green", StringComparison.Ordinal);

		// Assert
		await Assert.That(iconIdx).IsLessThan(viewsIdx);
		await Assert.That(colorIdx).IsGreaterThan(viewsIdx);
	}

	[Test]
	public async Task Generate_ElementWithUnknownState_DefaultStateStyleRulesAlwaysEmitted()
	{
		// Arrange
		// Even when no element carries a state tag, all 8 known state style rules are always
		// emitted so the generated file stays stable across state-change events.
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
					State = null,
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert — all known state style rules appear in the views section.
		await Assert.That(dsl).Contains("style element.tag = #aspire-run-state-starting");
		await Assert.That(dsl).Contains("style element.tag = #aspire-run-state-running");
		await Assert.That(dsl).Contains("style element.tag = #aspire-run-state-failedtostart");

		// The model section (before views {) must not contain any color property.
		var viewsIdx = dsl.IndexOf("views {", StringComparison.Ordinal);
		await Assert.That(dsl[..viewsIdx]).DoesNotContain("color");
	}

	[Test]
	public async Task Generate_IncludeDefaultStateStyles_False_DoesNotRenderTagStyleRules()
	{
		// Arrange
		// When IncludeDefaultStateStyles is false, no tag-predicate style rules should be emitted
		// even when elements carry state tags.
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
					State = KnownResourceStates.Running,
					Tags = ["aspire-run-state-running"],
				},
			],
			Relationships = [],
		};

		AspireC4DiagramOptions opts = new()
		{
			Title = DefaultOptions.Title,
			OutputDirectory = DefaultOptions.OutputDirectory,
			FileName = DefaultOptions.FileName,
			IncludeDefaultStateStyles = false,
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, opts);

		// Assert
		await Assert.That(dsl).DoesNotContain("style element.tag");
		await Assert.That(dsl).DoesNotContain("color ");
	}

	[Test]
	public async Task Generate_IncludeDefaultStateStyles_True_EmptyModel_AllStateTagsDeclaredInSpecification()
	{
		// Arrange
		// All 8 known state tags must appear in the specification block even when no element
		// currently carries any of them, so the generated file is stable across state changes.

		// Act
		var dsl = LikeC4DSLGenerator.Generate(LikeC4Model.Empty, DefaultOptions);

		// Assert — every known state tag is declared in the specification block.
		await Assert.That(dsl).Contains("tag aspire-run-state-starting");
		await Assert.That(dsl).Contains("tag aspire-run-state-waiting");
		await Assert.That(dsl).Contains("tag aspire-run-state-running");
		await Assert.That(dsl).Contains("tag aspire-run-state-stopping");
		await Assert.That(dsl).Contains("tag aspire-run-state-exited");
		await Assert.That(dsl).Contains("tag aspire-run-state-finished");
		await Assert.That(dsl).Contains("tag aspire-run-state-runtimeunhealthy");
		await Assert.That(dsl).Contains("tag aspire-run-state-failedtostart");
	}

	[Test]
	public async Task Generate_IncludeDefaultStateStyles_True_EmptyModel_AllStateStyleRulesEmittedInViews()
	{
		// Arrange
		// All 8 known state style rules must appear in the views block even when no element
		// currently carries any of them, so the generated file is stable across state changes.

		// Act
		var dsl = LikeC4DSLGenerator.Generate(LikeC4Model.Empty, DefaultOptions);

		// Assert — every known state tag has a style rule in the views block.
		var viewsIdx = dsl.IndexOf("views {", StringComparison.Ordinal);
		await Assert
			.That(dsl.IndexOf("style element.tag = #aspire-run-state-starting", viewsIdx, StringComparison.Ordinal))
			.IsGreaterThan(viewsIdx);
		await Assert
			.That(dsl.IndexOf("style element.tag = #aspire-run-state-running", viewsIdx, StringComparison.Ordinal))
			.IsGreaterThan(viewsIdx);
		await Assert
			.That(
				dsl.IndexOf("style element.tag = #aspire-run-state-failedtostart", viewsIdx, StringComparison.Ordinal)
			)
			.IsGreaterThan(viewsIdx);
	}

	[Test]
	public async Task Generate_IncludeDefaultStateStyles_False_EmptyModel_NoStateTagsInSpecification()
	{
		// Arrange
		AspireC4DiagramOptions opts = new()
		{
			Title = DefaultOptions.Title,
			OutputDirectory = DefaultOptions.OutputDirectory,
			FileName = DefaultOptions.FileName,
			IncludeDefaultStateStyles = false,
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(LikeC4Model.Empty, opts);

		// Assert — when opted out, no state tags are injected.
		await Assert.That(dsl).DoesNotContain("tag aspire-run-state-");
		await Assert.That(dsl).DoesNotContain("style element.tag");
	}

	[Test]
	public async Task Generate_ElementWithTags_EmitsTagsInSpecAndBody()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
					Tags = ["external", "deprecated"],
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Tags declared in specification block.
		// Assert
		await Assert.That(dsl).Contains("tag external");
		await Assert.That(dsl).Contains("tag deprecated");
		// Tags applied in element body.
		await Assert.That(dsl).Contains("#external");
		await Assert.That(dsl).Contains("#deprecated");
		// Tag application must appear before the views block (i.e. in model).
		var modelIdx = dsl.IndexOf("model {", StringComparison.Ordinal);
		var viewsIdx = dsl.IndexOf("views {", StringComparison.Ordinal);
		var tagApplyIdx = dsl.IndexOf("#external", StringComparison.Ordinal);
		await Assert.That(tagApplyIdx).IsGreaterThan(modelIdx);
		await Assert.That(tagApplyIdx).IsLessThan(viewsIdx);
	}

	[Test]
	public async Task Generate_TagsFromMultipleElements_DeclaredOnceInSpec()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
					Tags = ["external"],
				},
				new LikeC4Element
				{
					Name = "svc",
					Label = "SVC",
					Kind = LikeC4ElementKind.Component,
					Tags = ["external"],
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		var count = CountOccurrences(dsl, "tag external");
		// Assert
		await Assert.That(count).IsEqualTo(1);
	}

	[Test]
	public async Task Generate_TagsStoredWithoutHash_SpecAndBodyFormattedCorrectly()
	{
		// Arrange
		// Tags stored in the model must be without '#'; the generator adds '#' in the body
		// and emits the bare name in the spec. This test guards against double-hashing.
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
					Tags = ["external"],
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("tag external");
		await Assert.That(dsl).Contains("#external");
		await Assert.That(dsl).DoesNotContain("##external");
		await Assert.That(dsl).DoesNotContain("tag #external");
	}

	[Test]
	public async Task Generate_ElementWithLinks_EmitsLinkLines()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
					Links =
					[
						new LikeC4Link("https://example.com/docs", "Docs"),
						new LikeC4Link("https://example.com/src"),
					],
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("link https://example.com/docs 'Docs'");
		await Assert.That(dsl).Contains("link https://example.com/src");
		await Assert.That(dsl).DoesNotContain("link https://example.com/src '");
	}

	[Test]
	public async Task Generate_ElementWithMetadata_EmitsMetadataBlock()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
					Metadata = [new LikeC4Metadata("owner", "platform-team"), new LikeC4Metadata("tier", "1")],
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("metadata {");
		await Assert.That(dsl).Contains("owner 'platform-team'");
		await Assert.That(dsl).Contains("tier '1'");
	}

	[Test]
	public async Task Generate_RelationshipWithTags_EmitsTagsInSpecAndBody()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "a",
					Label = "A",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "b",
					Label = "B",
					Kind = LikeC4ElementKind.Component,
				},
			],
			Relationships =
			[
				new LikeC4Relationship
				{
					SourceName = "a",
					TargetName = "b",
					Tags = ["internal"],
				},
			],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("tag internal");
		await Assert.That(dsl).Contains("#internal");
	}

	[Test]
	public async Task Generate_RelationshipWithLinks_EmitsLinkLines()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "a",
					Label = "A",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "b",
					Label = "B",
					Kind = LikeC4ElementKind.Component,
				},
			],
			Relationships =
			[
				new LikeC4Relationship
				{
					SourceName = "a",
					TargetName = "b",
					Links = [new LikeC4Link("https://runbook.example.com")],
				},
			],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("link https://runbook.example.com");
	}

	[Test]
	public async Task Generate_RelationshipWithMetadata_EmitsMetadataBlock()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "a",
					Label = "A",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "b",
					Label = "B",
					Kind = LikeC4ElementKind.Component,
				},
			],
			Relationships =
			[
				new LikeC4Relationship
				{
					SourceName = "a",
					TargetName = "b",
					Metadata = [new LikeC4Metadata("retries", "3")],
				},
			],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("metadata {");
		await Assert.That(dsl).Contains("retries '3'");
	}

	[Test]
	[Arguments(2)]
	[Arguments(5)]
	[Arguments(10)]
	[Arguments(50)]
	public async Task Generate_RelationshipWithDuplicateMetadataKeys_EmitsAllMetadataValues(int metadataCount)
	{
		// Arrange
		var metadataKey = $"retries_{metadataCount}";
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "a",
					Label = "A",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "b",
					Label = "B",
					Kind = LikeC4ElementKind.Component,
				},
			],
			Relationships =
			[
				new LikeC4Relationship
				{
					SourceName = "a",
					TargetName = "b",
					Metadata =
					[
						.. Enumerable.Range(0, metadataCount).Select(i => new LikeC4Metadata(metadataKey, $"{i + 1}")),
					],
				},
			],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		var occurrences = CountOccurrences(dsl, $"{metadataCount} '");

		// Assert
		await Assert.That(occurrences).IsEqualTo(metadataCount);
	}

	[Test]
	[Arguments(2)]
	[Arguments(5)]
	[Arguments(10)]
	[Arguments(50)]
	public async Task Generate_ElementWithDuplicateMetadataKeys_EmitsAllMetadataValues(int metadataCount)
	{
		// Arrange
		var metadataKey = $"retries_{metadataCount}";
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "a",
					Label = "A",
					Kind = LikeC4ElementKind.Component,
					Metadata =
					[
						.. Enumerable.Range(0, metadataCount).Select(i => new LikeC4Metadata(metadataKey, $"{i + 1}")),
					],
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		var occurrences = CountOccurrences(dsl, $"{metadataCount} '");

		// Assert
		await Assert.That(occurrences).IsEqualTo(metadataCount);
	}

	[Test]
	public async Task Generate_RelationshipWithNavigateTo_EmitsNavigateToLine()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "a",
					Label = "A",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "b",
					Label = "B",
					Kind = LikeC4ElementKind.Component,
				},
			],
			Relationships =
			[
				new LikeC4Relationship
				{
					SourceName = "a",
					TargetName = "b",
					NavigateTo = "detail-flow",
				},
			],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("navigateTo detail-flow");
	}

	[Test]
	public async Task Generate_RelationshipWithNavigateTo_OpensBodyBlock()
	{
		// Arrange
		// navigateTo alone (no technology/description/etc) must still open the { } body block.
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "a",
					Label = "A",
					Kind = LikeC4ElementKind.Component,
				},
				new LikeC4Element
				{
					Name = "b",
					Label = "B",
					Kind = LikeC4ElementKind.Component,
				},
			],
			Relationships =
			[
				new LikeC4Relationship
				{
					SourceName = "a",
					TargetName = "b",
					NavigateTo = "my-view",
				},
			],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// The relationship body must be opened with { and closed with }.
		// Assert
		await Assert.That(dsl).Contains("a -> b {");
		await Assert.That(dsl).Contains("navigateTo my-view");
	}

	[Test]
	public async Task Generate_CustomElementKindSpec_EmittedInSpecification()
	{
		// Arrange
		AspireC4DiagramOptions opts = new()
		{
			Title = "Test",
			OutputDirectory = ".",
			ElementKindSpecs =
			[
				new LikeC4ElementKindSpec("queue")
					.WithNotation("Message Queue")
					.WithTechnology("RabbitMQ")
					.WithStyle(
						new LikeC4ElementKindStyle(null, null, null, null, null) { Shape = "queue", Color = "amber" }
					),
			],
		};

		LikeC4Model model = new() { Elements = [], Relationships = [] };
		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, opts);

		// Kind declared even though no elements use it.
		// Assert
		await Assert.That(dsl).Contains("element queue {");
		await Assert.That(dsl).Contains("notation 'Message Queue'");
		await Assert.That(dsl).Contains("technology 'RabbitMQ'");
		await Assert.That(dsl).Contains("style {");
		await Assert.That(dsl).Contains("shape queue");
		await Assert.That(dsl).Contains("color amber");
	}

	[Test]
	public async Task Generate_ElementKindMatchingCustomSpec_EmitsFullBody()
	{
		// Arrange
		AspireC4DiagramOptions opts = new()
		{
			Title = "Test",
			OutputDirectory = ".",
			ElementKindSpecs = [new LikeC4ElementKindSpec("component") { Notation = "Component" }],
		};

		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, opts);

		// element kind declared once with the notation body.
		// Assert
		await Assert.That(dsl).Contains("element component {");
		await Assert.That(dsl).Contains("notation 'Component'");
		var count = CountOccurrences(dsl, "element component");
		await Assert.That(count).IsEqualTo(1);
	}

	[Test]
	public async Task Generate_ElementWithGroup_EmitsGroupBlockInViews()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
					Group = "Frontend",
				},
				new LikeC4Element
				{
					Name = "db",
					Label = "DB",
					Kind = LikeC4ElementKind.Database,
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Group block inside views.
		// Assert
		await Assert.That(dsl).Contains("group 'Frontend' {");
		await Assert.That(dsl).Contains("include api");

		var viewsIdx = dsl.IndexOf("views {", StringComparison.Ordinal);
		var groupIdx = dsl.IndexOf("group 'Frontend'", StringComparison.Ordinal);
		var includeStarIdx = dsl.IndexOf("include *", StringComparison.Ordinal);
		await Assert.That(groupIdx).IsGreaterThan(viewsIdx);
		// Groups must come before `include *` so LikeC4 renders them correctly.
		await Assert.That(groupIdx).IsLessThan(includeStarIdx);

		// db has no group — should NOT be inside a group block.
		await Assert.That(dsl).DoesNotContain("include db");
	}

	[Test]
	public async Task Generate_MultipleGroups_EachGroupEmitted()
	{
		// Arrange
		LikeC4Model model = new()
		{
			Elements =
			[
				new LikeC4Element
				{
					Name = "ui",
					Label = "UI",
					Kind = LikeC4ElementKind.Component,
					Group = "Frontend",
				},
				new LikeC4Element
				{
					Name = "api",
					Label = "API",
					Kind = LikeC4ElementKind.Component,
					Group = "Backend",
				},
				new LikeC4Element
				{
					Name = "svc",
					Label = "SVC",
					Kind = LikeC4ElementKind.Component,
					Group = "Backend",
				},
			],
			Relationships = [],
		};

		// Act
		var dsl = LikeC4DSLGenerator.Generate(model, DefaultOptions);

		// Assert
		await Assert.That(dsl).Contains("group 'Frontend' {");
		await Assert.That(dsl).Contains("include ui");
		await Assert.That(dsl).Contains("group 'Backend' {");
		// api and svc both in Backend group.
		await Assert.That(dsl).Contains("include api, svc");
	}

	[System.Text.RegularExpressions.GeneratedRegex(@"(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) UTC")]
	private static partial System.Text.RegularExpressions.Regex TimeStampRegex();
}
