<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<IsPackable>true</IsPackable>
		<AssemblyTitle>AspireC4 Hosting</AssemblyTitle>
		<Description>Aspire hosting extension for the AspireC4 plugin, generating a dynamic LikeC4 architecture diagram for your Aspire application.</Description>
		<COPYRIGHT_YEAR>2026</COPYRIGHT_YEAR>
		<PackageId>AspireC4.Hosting</PackageId>
		<Title>AspireC4.Hosting - Aspire LikeC4 Visualisation</Title>
		<Authors>Purview Contributors</Authors>
		<Copyright>Purview-Dev., $(COPYRIGHT_YEAR) | All rights reserved.</Copyright>
		<PackageIcon>likec4-logo.png</PackageIcon>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/purview-dev/aspirec4</RepositoryUrl>
		<PackageProjectUrl>$(PurviewProjectUrl)</PackageProjectUrl>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>aspire;dotnet;aspnetcore;c4;likec4;architecture;diagram;visualisation;visualization;</PackageTags>
		<IncludeSymbols>true</IncludeSymbols>
		<!--
			Opting into the Aspire integration analysers - hoping it'll help me to
			figure out some issues with the TypeScript exports.
		-->
		<EnableAspireIntegrationAnalyzers>true</EnableAspireIntegrationAnalyzers>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="BuildResources\likec4-icons.json" />
	</ItemGroup>

	<ItemGroup>
		<None
			Include="$(MSBuildThisFileDirectory)..\..\..\assets\images\likec4\likec4-logo.png"
			Link="Sdk/likec4-logo.png"
		/>
		<None Include="$(MSBuildThisFileDirectory)..\..\..\LICENSE.md" Link="Sdk/LICENSE.md" />
		<None Include="$(MSBuildThisFileDirectory)..\..\..\README.md" Link="Sdk/README.md" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference
			Include="..\SourceGenerators\SourceGenerators.csproj"
			OutputItemType="Analyzer"
			ReferenceOutputAssembly="false"
			PrivateAssets="all"
			IsAspireProjectResource="false"
		/>
	</ItemGroup>

	<ItemGroup>
		<Using Include="Aspire.Hosting.ApplicationModel" />
	</ItemGroup>
</Project>
