using System.Text;
using Aspire.Hosting.AspireC4.LikeC4.Models;

namespace Aspire.Hosting.AspireC4.LikeC4.Generators;

/// <summary>
/// Generates a LikeC4 DSL (<c>.c4</c>) string from a <see cref="LikeC4Model"/>.
/// </summary>
public static class LikeC4DSLGenerator
{
	/// <summary>Generates a LikeC4 DSL string from the given model and options.</summary>
	public static string Generate(LikeC4Model model, AspireC4DiagramOptions options)
	{
		ArgumentNullException.ThrowIfNull(model);
		ArgumentNullException.ThrowIfNull(options);

		StringBuilder sb = new(512);

		var now = DateTimeOffset.UtcNow;
		sb.AppendLine("// =============================================================================");
		sb.Append("// AUTO-GENERATED by AspireC4 — ")
			.AppendLine(now.ToString("yyyy-MM-dd HH:mm:ss 'UTC'", System.Globalization.CultureInfo.InvariantCulture));
		sb.AppendLine("// Do not edit this file manually. Any changes will be overwritten on the");
		sb.AppendLine("// next diagram regeneration (on Aspire startup or resource state change).");
		sb.AppendLine("// See https://github.com/purview-dev/aspirec4 for more information.");
		sb.AppendLine("// =============================================================================");
		sb.AppendLine();

		WriteSpecification(sb, model, options);
		sb.AppendLine();
		WriteModel(sb, model, options);
		sb.AppendLine();
		WriteViews(sb, model, options);

		return sb.ToString();
	}

	static void WriteSpecification(StringBuilder sb, LikeC4Model model, AspireC4DiagramOptions options)
	{
		var elementKindsInModel = model.Elements.Select(e => e.Kind).ToHashSet();
		var allElementKinds = elementKindsInModel.Union(options.ElementKindSpecs.Select(s => s.Name)).OrderBy(k => k);

		var relationshipKindsInModel = model
			.Relationships.Where(r => !string.IsNullOrWhiteSpace(r.Kind))
			.Select(r => r.Kind!)
			.ToHashSet(StringComparer.OrdinalIgnoreCase);
		var allRelationshipKinds = relationshipKindsInModel
			.Union(options.RelationshipKindSpecs.Select(s => s.Name), StringComparer.OrdinalIgnoreCase)
			.OrderBy(k => k);

		var relationshipKindSpecsByName = options.RelationshipKindSpecs.ToDictionary(
			s => s.Name,
			StringComparer.OrdinalIgnoreCase
		);

		// Always include all known state tags so the specification block is stable regardless
		// of which states happen to be active right now — preventing needless file churn.
		var knownStateTags = options.IncludeDefaultStateStyles ? DefaultStateStyles.Keys : [];
		var allTags = model
			.Elements.SelectMany(e => e.Tags)
			.Concat(model.Relationships.SelectMany(r => r.Tags))
			.Concat(knownStateTags)
			.Distinct(StringComparer.OrdinalIgnoreCase)
			.OrderBy(t => t);

		var specsByName = options.ElementKindSpecs.ToDictionary(s => s.Name, StringComparer.OrdinalIgnoreCase);

		sb.AppendLine("specification {");

		foreach (var kind in allElementKinds)
		{
			if (specsByName.TryGetValue(kind, out var spec))
			{
				WriteElementKindSpec(sb, spec);
			}
			else
			{
				sb.Append("  element ").AppendLine(kind);
			}
		}

		foreach (var kind in allRelationshipKinds)
		{
			if (
				relationshipKindSpecsByName.TryGetValue(kind, out var relSpec)
				&& !string.IsNullOrWhiteSpace(relSpec.Technology)
			)
			{
				WriteRelationshipKindSpec(sb, relSpec);
			}
			else
			{
				sb.Append("  relationship ").AppendLine(kind);
			}
		}

		foreach (var tag in allTags)
		{
			sb.Append("  tag ").AppendLine(tag);
		}

		sb.AppendLine("}");
	}

	static void WriteElementKindSpec(StringBuilder sb, LikeC4ElementKindSpec spec)
	{
		var hasNotation = !string.IsNullOrWhiteSpace(spec.Notation);
		var hasTechnology = !string.IsNullOrWhiteSpace(spec.Technology);
		var style = spec.Style;
		var hasStyle =
			style is not null
			&& (
				!string.IsNullOrWhiteSpace(style.Shape)
				|| !string.IsNullOrWhiteSpace(style.Color)
				|| !string.IsNullOrWhiteSpace(style.Icon)
				|| !string.IsNullOrWhiteSpace(style.Border)
				|| style.Opacity.HasValue
			);

		if (!hasNotation && !hasTechnology && !hasStyle)
		{
			sb.Append("  element ").AppendLine(spec.Name);
			return;
		}

		sb.Append("  element ").Append(spec.Name).AppendLine(" {");

		if (hasNotation)
		{
			sb.Append("    notation '").Append(EscapeQuote(spec.Notation!)).AppendLine("'");
		}

		if (hasTechnology)
		{
			sb.Append("    technology '").Append(EscapeQuote(spec.Technology!)).AppendLine("'");
		}

		if (hasStyle)
		{
			sb.AppendLine("    style {");
			if (!string.IsNullOrWhiteSpace(style!.Shape))
			{
				sb.Append("      shape ").AppendLine(style.Shape);
			}

			if (!string.IsNullOrWhiteSpace(style.Color))
			{
				sb.Append("      color ").AppendLine(style.Color);
			}

			if (!string.IsNullOrWhiteSpace(style.Icon))
			{
				sb.Append("      icon ").AppendLine(style.Icon);
			}

			if (!string.IsNullOrWhiteSpace(style.Border))
			{
				sb.Append("      border ").AppendLine(style.Border);
			}

			if (style.Opacity.HasValue)
			{
				sb.Append("      opacity ").Append(style.Opacity.Value).AppendLine("%");
			}

			sb.AppendLine("    }");
		}

		sb.AppendLine("  }");
	}

	static void WriteRelationshipKindSpec(StringBuilder sb, LikeC4RelationshipKindSpec spec)
	{
		sb.Append("  relationship ").Append(spec.Name).AppendLine(" {");
		sb.Append("    technology '").Append(EscapeQuote(spec.Technology!)).AppendLine("'");
		sb.AppendLine("  }");
	}

	static void WriteModel(StringBuilder sb, LikeC4Model model, AspireC4DiagramOptions options)
	{
		sb.AppendLine("model {");

		// Top-level elements first, then nested.
		var topLevel = model.Elements.Where(e => e.ParentName is null).ToList();
		var nested = model
			.Elements.Where(e => e.ParentName is not null)
			.ToLookup(e => e.ParentName!, StringComparer.OrdinalIgnoreCase);

		foreach (var element in topLevel)
		{
			WriteElement(sb, element, "  ", nested);
		}

		sb.AppendLine();

		foreach (var rel in model.Relationships)
		{
			var hasKind = !string.IsNullOrWhiteSpace(rel.Kind);

			sb.Append("  ").Append(Sanitize(rel.SourceName));

			if (hasKind)
			{
				if (options.RelationshipKindSyntax == LikeC4RelationshipKindSyntax.Bracket)
				{
					sb.Append(" -[").Append(rel.Kind).Append("]-> ");
				}
				else
				{
					sb.Append(" .").Append(rel.Kind).Append(' ');
				}
			}
			else
			{
				sb.Append(" -> ");
			}

			sb.Append(Sanitize(rel.TargetName));

			if (!string.IsNullOrWhiteSpace(rel.Label))
			{
				sb.Append(" '").Append(EscapeQuote(rel.Label)).Append('\'');
			}

			var hasTags = rel.Tags.Count > 0;
			var hasTechnology = !string.IsNullOrWhiteSpace(rel.Technology);
			var hasDescription = !string.IsNullOrWhiteSpace(rel.Description);
			var hasLinks = rel.Links.Count > 0;
			var hasMetadata = rel.Metadata.Count > 0;
			var hasNavigateTo = !string.IsNullOrWhiteSpace(rel.NavigateTo);

			if (hasTags || hasTechnology || hasDescription || hasLinks || hasMetadata || hasNavigateTo)
			{
				sb.AppendLine(" {");

				if (hasTags)
				{
					sb.Append("    ");
					foreach (var tag in rel.Tags)
					{
						sb.Append('#').Append(tag).Append(' ');
					}

					sb.AppendLine();
				}

				if (hasTechnology)
				{
					sb.Append("    technology '").Append(EscapeQuote(rel.Technology!)).AppendLine("'");
				}

				if (hasDescription)
				{
					sb.Append("    description '''").AppendLine();
					sb.Append(EscapeQuote(rel.Description!)).AppendLine();
					sb.AppendLine("    '''");
				}

				foreach (var link in rel.Links)
				{
					sb.Append("    link ").Append(link.Uri);
					if (!string.IsNullOrWhiteSpace(link.Title))
					{
						sb.Append(" '").Append(EscapeQuote(link.Title)).Append('\'');
					}

					sb.AppendLine();
				}

				if (hasMetadata)
				{
					sb.AppendLine("    metadata {");
					foreach (var (key, value) in rel.Metadata)
					{
						sb.Append("      ").Append(key).Append(" '").Append(EscapeQuote(value)).AppendLine("'");
					}

					sb.AppendLine("    }");
				}

				if (hasNavigateTo)
				{
					sb.Append("    navigateTo ").AppendLine(rel.NavigateTo!);
				}

				sb.AppendLine("  }");
			}
			else
			{
				sb.AppendLine();
			}
		}

		sb.AppendLine("}");
	}

	static void WriteElement(
		StringBuilder sb,
		LikeC4Element element,
		string indent,
		ILookup<string, LikeC4Element> nested
	)
	{
		sb.Append(indent)
			.Append(Sanitize(element.Name))
			.Append(" = ")
			.Append(element.Kind)
			.Append(" '")
			.Append(EscapeQuote(element.Label))
			.Append('\'');

		var children = nested[element.Name];
		var hasTags = element.Tags.Count > 0;
		var hasTechnology = !string.IsNullOrWhiteSpace(element.Technology);
		var hasDescription = !string.IsNullOrWhiteSpace(element.Description);
		var hasSummary = !string.IsNullOrWhiteSpace(element.Summary);
		var hasIcon = !string.IsNullOrWhiteSpace(element.Icon);
		var hasLinks = element.Links.Count > 0;
		var hasMetadata = element.Metadata.Count > 0;
		var hasChildren = children.Any();

		if (
			!hasTags
			&& !hasTechnology
			&& !hasDescription
			&& !hasSummary
			&& !hasIcon
			&& !hasLinks
			&& !hasMetadata
			&& !hasChildren
		)
		{
			sb.AppendLine();
			return;
		}

		sb.AppendLine(" {");

		if (hasTags)
		{
			sb.Append(indent).Append("  ");
			foreach (var tag in element.Tags)
			{
				sb.Append('#').Append(tag).Append(' ');
			}

			sb.AppendLine();
		}

		if (hasTechnology)
		{
			sb.Append(indent).Append("  technology '").Append(EscapeQuote(element.Technology!)).AppendLine("'");
		}

		if (hasSummary)
		{
			sb.Append(indent).Append("  summary '").Append(EscapeQuote(element.Summary!)).AppendLine("'");
		}

		if (hasDescription)
		{
			sb.Append(indent)
				.Append("  description '''")
				.AppendLine()
				.Append(EscapeQuote(element.Description!))
				.AppendLine()
				.AppendLine("  '''");
		}

		if (hasIcon)
		{
			sb.Append(indent).Append("  icon ").AppendLine(element.Icon!);
		}

		foreach (var link in element.Links)
		{
			sb.Append(indent).Append("  link ").Append(link.Uri);
			if (!string.IsNullOrWhiteSpace(link.Title))
			{
				sb.Append(" '").Append(EscapeQuote(link.Title)).Append('\'');
			}

			sb.AppendLine();
		}

		if (hasMetadata)
		{
			sb.Append(indent).AppendLine("  metadata {");
			foreach (var (key, value) in element.Metadata)
			{
				sb.Append(indent).Append("    ").Append(key).Append(" '").Append(EscapeQuote(value)).AppendLine("'");
			}

			sb.Append(indent).AppendLine("  }");
		}

		if (hasChildren)
		{
			foreach (var child in children)
			{
				WriteElement(sb, child, indent + "  ", nested);
			}
		}

		sb.Append(indent).AppendLine("}");
	}

	/// <summary>
	/// Style override (color and/or opacity) for a view-level style rule.
	/// A <see langword="null"/> value means "use the default".
	/// </summary>
	readonly record struct LikeC4ElementStyleOverride(string? Color, int? Opacity);

	/// <summary>
	/// Default tag-to-style mappings for the built-in <c>aspire-run-state-*</c> state tags.
	/// <para>
	/// Opacity is used to distinguish transitional from terminal states:
	/// <list type="bullet">
	///   <item><description><c>aspire-run-state-stopping</c> — 60 % opacity: visible but clearly winding down.</description></item>
	///   <item><description><c>aspire-run-state-exited</c> — 30 % opacity: very faded, fully inactive.</description></item>
	/// </list>
	/// </para>
	/// </summary>
	static readonly IReadOnlyDictionary<string, LikeC4ElementStyleOverride> DefaultStateStyles = new Dictionary<
		string,
		LikeC4ElementStyleOverride
	>(StringComparer.OrdinalIgnoreCase)
	{
		[LikeC4StateTags.Starting] = new("sky", null),
		[LikeC4StateTags.Waiting] = new("sky", null),
		[LikeC4StateTags.Running] = new("green", null),
		[LikeC4StateTags.Stopping] = new("slate", 60),
		[LikeC4StateTags.Exited] = new("muted", 30),
		[LikeC4StateTags.Finished] = new("muted", 30),
		[LikeC4StateTags.RuntimeUnhealthy] = new("amber", null),
		[LikeC4StateTags.FailedToStart] = new("red", null),
	};

	static void WriteViews(StringBuilder sb, LikeC4Model model, AspireC4DiagramOptions options)
	{
		var viewId = string.IsNullOrWhiteSpace(options.GeneratedViewId) ? "index" : options.GeneratedViewId;
		sb.AppendLine("views {");
		sb.Append("  view ").Append(viewId).AppendLine(" {");
		sb.Append("    title '").Append(EscapeQuote(options.ViewTitle)).AppendLine("'");
		if (!string.IsNullOrWhiteSpace(options.ViewDescription))
		{
			sb.Append("    description '''").AppendLine();
			sb.Append(EscapeQuote(options.ViewDescription)).AppendLine();
			sb.AppendLine("    '''");
		}

		if (model.Elements.Count == 0)
		{
			sb.AppendLine("    // No resources found");
		}
		else
		{
			// Groups must be declared before `include *` or they will not render correctly.
			var groups = model.Elements.Where(e => e.Group is not null).GroupBy(e => e.Group!).OrderBy(g => g.Key);

			foreach (var group in groups)
			{
				var members = string.Join(", ", group.Select(e => Sanitize(e.Name)));
				sb.Append("    group '").Append(EscapeQuote(group.Key)).AppendLine("' {");
				sb.Append("      include ").AppendLine(members);
				sb.AppendLine("    }");
			}

			sb.AppendLine("    include *");
		}

		// Emit tag-predicate style rules for all known state tags.
		// These are always emitted — even for empty models — so the views block is stable
		// regardless of which resources are currently active or what state they are in.
		// In LikeC4, element colors must be set via view-level style rules, not in the model block.
		if (options.IncludeDefaultStateStyles)
		{
			foreach (var (tag, styleOverride) in DefaultStateStyles)
			{
				sb.Append("    style element.tag = #").Append(tag).AppendLine(" {");
				if (styleOverride.Color is not null)
				{
					sb.Append("      color ").AppendLine(styleOverride.Color);
				}

				if (styleOverride.Opacity is not null)
				{
					sb.Append("      opacity ").Append(styleOverride.Opacity).AppendLine("%");
				}

				sb.AppendLine("    }");
			}
		}

		sb.AppendLine("  }");
		sb.AppendLine("}");
	}

	/// <summary>Replaces characters invalid in LikeC4 identifiers with underscores.</summary>
	static string Sanitize(string name) =>
		string.Create(
			name.Length,
			name,
			static (span, src) =>
			{
				for (var i = 0; i < src.Length; i++)
				{
					span[i] = char.IsLetterOrDigit(src[i]) || src[i] == '_' ? src[i] : '_';
				}
			}
		);

	/// <summary>Escapes single quotes in string values used inside LikeC4 quoted strings.</summary>
	static string EscapeQuote(string value) => value.Replace("'", "\\'", StringComparison.Ordinal);
}
