<Project>
	<PropertyGroup>
		<NamespacePrefix>Aspire.Hosting.AspireC4</NamespacePrefix>
	</PropertyGroup>

	<Import Sdk="Purview.DotNetProjectSdk" Project="Sdk.props" />

	<PropertyGroup>
		<!-- Matching the Aspire.* minimum framework -->
		<TargetFramework>net8.0</TargetFramework>
		<NoWarn>$(NoWarn);ASPIREATS001</NoWarn>
		<ExcludeMSTelemetryExtension>true</ExcludeMSTelemetryExtension>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
	</PropertyGroup>
	<PropertyGroup Condition="'$(IsTestProject)' == 'true'">
		<NoWarn>$(NoWarn);CA1034;CA2234;</NoWarn>
	</PropertyGroup>

	<PropertyGroup Label="Purview site URL metadata">
		<PurviewHomepage>https://purview.dev/</PurviewHomepage>
		<PurviewProjectUrl>$(PurviewHomepage)projects/aspirec4/</PurviewProjectUrl>
		<PurviewDocsUrl>$(PurviewHomepage)docs/aspirec4/</PurviewDocsUrl>
	</PropertyGroup>
</Project>
