<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.Testing" />
		<PackageReference Include="TUnit.Aspire" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\TestAppHost\TestAppHost.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content
			Include="..\..\..\assets\likec4-extensions\**\*"
			Link="Resources\likec4\extensions\%(RecursiveDir)%(Filename)%(Extension)"
			CopyToOutputDirectory="PreserveNewest"
		/>
		<Content
			Include="..\..\..\assets\images\**\*"
			Link="Resources\likec4\images\%(RecursiveDir)%(Filename)%(Extension)"
			CopyToOutputDirectory="PreserveNewest"
		/>
	</ItemGroup>
</Project>
